### ISSUE TITLE
Non-deterministic errors when running TCP

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/VRTstatistics#4]
When TCP is used for point cloud delivery, the session runs just fine within the built application. However, the following errors can be observed non-deterministically:

**Error 1**

```
+ GET http://10.10.130.255:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis.cwi.nl/VR2Gather/Player.log
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender-unity-log.txt size=680254
+ GET http://10.10.129.141:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis.cwi.nl/VR2Gather/Player.log
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver-unity-log.txt size=43358
+ GET http://10.10.130.255:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis_cwi_nl/VR2Gather/VRTstatistics-example.txt
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender.log size=922287
+ GET http://10.10.129.141:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis_cwi_nl/VR2Gather/VRTstatistics-example.txt
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver.log size=1894380
+ GET http://10.10.130.255:5001/getfile fullpath=rusage.log
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender-rusage.log size=99693
+ GET http://10.10.129.141:5001/getfile fullpath=rusage.log
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver-rusage.log size=96430
C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver.log: warning: missing end of session
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\.venv\Scripts\VRTstatistics-ingest.exe\__main__.py", line 7, in <module>
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\scripts\ingest.py", line 106, in main
    ok = combine(args.annotator, senderdata, receiverdata, outputdata)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\annotator.py", line 384, in combine
    annotate_receiver.collect()
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\annotator.py", line 234, in collect
    rr = self.datastore.find_all_records(f'component == "{recv_pc_reader_umbrella}" and "pull_thread" in record', "receiver pc readers")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\datastore.py", line 183, in find_all_records
    raise DataStoreError(f"missing {descr}")
VRTstatistics.datastore.DataStoreError: missing receiver pc readers
```

**Error 2**

```
+ GET http://10.10.129.141:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis.cwi.nl/VR2Gather/Player.log
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender-unity-log.txt size=43300
+ GET http://10.10.130.255:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis.cwi.nl/VR2Gather/Player.log
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver-unity-log.txt size=680303
+ GET http://10.10.129.141:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis_cwi_nl/VR2Gather/VRTstatistics-example.txt
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender.log size=1893654
+ GET http://10.10.130.255:5001/getfile fullpath=C:/Users/jvdrhoof/AppData/LocalLow/dis_cwi_nl/VR2Gather/VRTstatistics-example.txt
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver.log size=927123
+ GET http://10.10.129.141:5001/getfile fullpath=rusage.log
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender-rusage.log size=96203
+ GET http://10.10.130.255:5001/getfile fullpath=rusage.log
- GET http://10.10.130.255:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/receiver-rusage.log size=99361
C:/Users/jvdrhoof/GitHub/mmsys_2025_measurements/sandbox/jeroen/results_loot_tcp/sender.log: warning: missing end of session
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\.venv\Scripts\VRTstatistics-ingest.exe\__main__.py", line 7, in <module>
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\scripts\ingest.py", line 106, in main
    ok = combine(args.annotator, senderdata, receiverdata, outputdata)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\annotator.py", line 383, in combine
    annotate_sender.collect()
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\annotator.py", line 130, in collect
    r = self.datastore.find_first_record('"PointCloudPipelineSelf" in component and "self" in record and self == 1', "sender pc pipeline")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\datastore.py", line 169, in find_first_record
    raise DataStoreError(f"missing {descr}, predicate: {repr(predicate)}")
VRTstatistics.datastore.DataStoreError: missing sender pc pipeline, predicate: '"PointCloudPipelineSelf" in component and "self" in record and self == 1'
```

**Comment by jvdrhoof** [comment]
@jackjansen, [this directory](https://github.com/jvdrhoof/mmsys_2025/tree/main/sandbox/jeroen) contains several session log files for TCP, SocketIO and WebRTC. Can you have a look?

**Comment by jackjansen** [comment]
These should have been fixed (or at least worked-around).

Also, the annotator is now more verbose, so if the issue still exist: please reopen and attach a new output log (because it will contain better error messages) and attach the `sender.log` and `receiver.log` (or provide a pointer).

The annotator output explains what information it found, and in which line of which log file. And if it can't find something it needs it will give a better message about what it was looking for. You _may_ be able to work out yourself what is going wrong.
