### ISSUE TITLE
Annotator Not Working on Ashu's Laptop

### ISSUE THREAD

**Issue by ashutosh3308** [cwi-dis/VRTstatistics#5]
`Results/receiver.log: warning: missing end of session
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ashutosh\Desktop\VR2Gather_Projects_new\VRTstatistics\VRTstatistics\.venv\Scripts\VRTstatistics-ingest.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ashutosh\Desktop\VR2Gather_Projects_new\VRTstatistics\VRTstatistics\src\VRTstatistics\scripts\ingest.py", line 106, in main
    ok = combine(args.annotator, senderdata, receiverdata, outputdata)
  File "C:\Users\Ashutosh\Desktop\VR2Gather_Projects_new\VRTstatistics\VRTstatistics\src\VRTstatistics\annotator.py", line 384, in combine
    annotate_receiver.collect()
  File "C:\Users\Ashutosh\Desktop\VR2Gather_Projects_new\VRTstatistics\VRTstatistics\src\VRTstatistics\annotator.py", line 234, in collect
    rr = self.datastore.find_all_records(f'component == "{recv_pc_reader_umbrella}" and "pull_thread" in record', "receiver pc readers")
  File "C:\Users\Ashutosh\Desktop\VR2Gather_Projects_new\VRTstatistics\VRTstatistics\src\VRTstatistics\datastore.py", line 183, in find_all_records
    raise DataStoreError(f"missing {descr}")
VRTstatistics.datastore.DataStoreError: missing receiver pc readers`

**Comment by jackjansen** [comment]
Should be fixed when you upgrade cwipc_unity.

**Comment by ashutosh3308** [comment]
@jackjansen: Yes, it works now. I tested it in the morning today.
