### ISSUE TITLE
KeyError: 'component'

### ISSUE THREAD

**Issue by jvdrhoof** [cwi-dis/VRTstatistics#7]
Running the latest version of the orchestrator and VRTstatistics, I see the following error message:

```
+ GET http://10.10.129.141:5001/getfile fullpath=rusage.log
- GET http://10.10.129.141:5001/getfile filename=C:/Users/jvdrhoof/GitHub/mmsys_2025/sandbox/jeroen/vwall_from_igent/results_socketio_synthetic-40_untiled_50ms\receiver-rusage.log size=94073
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\.venv\Scripts\VRTstatistics-ingest.exe\__main__.py", line 7, in <module>
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\scripts\ingest.py", line 103, in main
    receiverdata.load()
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\datastore.py", line 37, in load
    self.load_log()
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\datastore.py", line 60, in load_log
    parser.check()
  File "C:\Users\jvdrhoof\GitHub\VRTstatistics\src\VRTstatistics\parser.py", line 100, in check
    if not entry["component"] == "OrchestratorController":
           ~~~~~^^^^^^^^^^^^^
KeyError: 'component'
```

Can this be resolved?

**Comment by jackjansen** [comment]
@jvdrhoof can you attach the corresponding data files? Specifically `sender.log` and `receiver.log`.

This "shouldn't happen", it means there's a line in the log files that does not conform to the required format...

Actually: also upload the unity logs. please.

**Comment by jvdrhoof** [comment]
The error no longer occurs with the newest version of VR2Gather and VRTstatistics.
